query {
  damageFiles {
    items {
      damages {
         items {
          documents {
            items {
              id
              title
              createdAt
              createdAtDecorated
            }
          }
        }
        }
      }
    }
}
  